# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
