# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_hobby_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeofwork',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='placeofwork',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
